
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5



  redis:
    image: redis:latest

  django:
    build: .
    command: sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  backend:
    build: .  # Использует Dockerfile в корне проекта
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SECRET_KEY: ${SECRET_KEY}
      DJANGO_DEBUG: ${DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_DATABASE_NAME: ${NAME}
      DJANGO_DATABASE_USER: ${USER}
      DJANGO_DATABASE_PASSWORD: ${PASSWORD}
      DJANGO_DATABASE_HOST: db
      DJANGO_DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8000/health/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build: .
    command: celery -A config.celery_app worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A config.celery_app beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}


  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443" # Add 443 port for HTTPS
    depends_on:
      - django
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles

volumes:
  postgres_data:
  static_volume:
  media_volume: